### ISSUE TITLE
Compile on Mac M1

### ISSUE THREAD

**Issue by alexarcherr** [l-4-l/ha#1]
Hello! How do you think, Is it possible to compile this archiver on Mac M1 with clang/gcc without total rewriting?

**Comment by l-4-l** [comment]
Hi @alexarcherr , I did it on MacOS M2, see the branch https://github.com/l-4-l/ha/tree/macos-m1

**Comment by alexarcherr** [comment]
Thanks a lot! FYI: This branch successfully built and run on my Mac M1. But when I try to extract old HA-file, it warn "ha: Wrong size for U32B, ha: Wrong size for S32B" due extraction and result TXT-file seems corrupted :( 
![Screenshot 2024-06-17 at 21 04 59](https://github.com/l-4-l/ha/assets/11070395/cc72d751-abeb-4ed7-80be-e51758eb2405)
[HARMS01.HA.zip](https://github.com/user-attachments/files/15875234/HARMS01.HA.zip)

**Comment by l-4-l** [comment]
> Thanks a lot! FYI: This branch successfully built and run on my Mac M1. But when I try to extract old HA-file, it warn "ha: Wrong size for U32B, ha: Wrong size for S32B" due extraction and result TXT-file seems corrupted

Thank you for testing, I fixed it, please pull and rebuild.
